/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface EnsAdd {
    'match': MatchResults;
  }
  interface EnsAddAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface EnsDetails {
    'match': MatchResults;
  }
  interface EnsDetailsAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface EnsFind {}
  interface EnsFindAttributes extends StencilHTMLAttributes {}

  interface EnsList {}
  interface EnsListAttributes extends StencilHTMLAttributes {}

  interface FormDetails {
    'match': MatchResults;
  }
  interface FormDetailsAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface FormList {}
  interface FormListAttributes extends StencilHTMLAttributes {}

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'EnsAdd': Components.EnsAdd;
    'EnsDetails': Components.EnsDetails;
    'EnsFind': Components.EnsFind;
    'EnsList': Components.EnsList;
    'FormDetails': Components.FormDetails;
    'FormList': Components.FormList;
    'SpiHeader': Components.SpiHeader;
    'SpiHome': Components.SpiHome;
    'SpiRoot': Components.SpiRoot;
  }

  interface StencilIntrinsicElements {
    'ens-add': Components.EnsAddAttributes;
    'ens-details': Components.EnsDetailsAttributes;
    'ens-find': Components.EnsFindAttributes;
    'ens-list': Components.EnsListAttributes;
    'form-details': Components.FormDetailsAttributes;
    'form-list': Components.FormListAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-root': Components.SpiRootAttributes;
  }


  interface HTMLEnsAddElement extends Components.EnsAdd, HTMLStencilElement {}
  var HTMLEnsAddElement: {
    prototype: HTMLEnsAddElement;
    new (): HTMLEnsAddElement;
  };

  interface HTMLEnsDetailsElement extends Components.EnsDetails, HTMLStencilElement {}
  var HTMLEnsDetailsElement: {
    prototype: HTMLEnsDetailsElement;
    new (): HTMLEnsDetailsElement;
  };

  interface HTMLEnsFindElement extends Components.EnsFind, HTMLStencilElement {}
  var HTMLEnsFindElement: {
    prototype: HTMLEnsFindElement;
    new (): HTMLEnsFindElement;
  };

  interface HTMLEnsListElement extends Components.EnsList, HTMLStencilElement {}
  var HTMLEnsListElement: {
    prototype: HTMLEnsListElement;
    new (): HTMLEnsListElement;
  };

  interface HTMLFormDetailsElement extends Components.FormDetails, HTMLStencilElement {}
  var HTMLFormDetailsElement: {
    prototype: HTMLFormDetailsElement;
    new (): HTMLFormDetailsElement;
  };

  interface HTMLFormListElement extends Components.FormList, HTMLStencilElement {}
  var HTMLFormListElement: {
    prototype: HTMLFormListElement;
    new (): HTMLFormListElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLElementTagNameMap {
    'ens-add': HTMLEnsAddElement
    'ens-details': HTMLEnsDetailsElement
    'ens-find': HTMLEnsFindElement
    'ens-list': HTMLEnsListElement
    'form-details': HTMLFormDetailsElement
    'form-list': HTMLFormListElement
    'spi-header': HTMLSpiHeaderElement
    'spi-home': HTMLSpiHomeElement
    'spi-root': HTMLSpiRootElement
  }

  interface ElementTagNameMap {
    'ens-add': HTMLEnsAddElement;
    'ens-details': HTMLEnsDetailsElement;
    'ens-find': HTMLEnsFindElement;
    'ens-list': HTMLEnsListElement;
    'form-details': HTMLFormDetailsElement;
    'form-list': HTMLFormListElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-root': HTMLSpiRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
